### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by piyueh** [FND/markdown-checklist#13]
Thanks for open-sourcing this project! Is there any license file in this repo? On the [pypi page](https://pypi.org/project/markdown-checklist/), it says MIT license. But I couldn't find a license statement in this repository. Without an explicit `LICENSE` file, I think no one by default has permission to use this package, even though the source code is open.

**Comment by FND** [comment]
Hey, thanks for dropping by.

I have no reservations about adding a `LICENSE` file to the repo. Out of curiosity: In what sense does it make a difference to you; is this required by your organization perhaps, or more personal interest?

**Comment by piyueh** [comment]
I am packaging a QT markdown viewer -- [*mdpreview*](https://github.com/fboender/mdpreview) (I'm not the author of it) -- as an Arch Linux AUR package so that Arch users can install it with a package manager. However, I found *mdpreview* depends on *markdown-checklist*. That means I also have to package *markdown-checklist* as an AUR package. But without a license statement, legally speaking, I am not authorized to use and redistribute *markdown-checklist*, which prohibits me from packing it to Arch AUR. Because it's going to be on AUR's public website, so I have to consider more from the legal aspect.

Legally speaking, if *mdpreview*'s author did not obtain your explicit permission in the past, it cannot use *markdown-checklist* as a dependency, either. And the result is that no one can use *mdpreview*. [Here](https://opensource.stackexchange.com/a/1721) has an explanation.

(In the end, I still packaged *markdown-checklist* to AUR (see [here](https://aur.archlinux.org/packages/python-markdown-checklist-git/)) by assuming the MIT license mentioned on PyPi page applies. If you object it, please let me know, and I'll remove it from AUR.)

**Comment by FND** [comment]
Oh, I didn't know about mdpreview - thanks for the thorough explanation, as well as for your work as package maintainer!

I've tried adding a license, but failed to release a new version; see #14. (This is what I was hesitant to revive this project in the first place... )

**Comment by FND** [comment]
Should now be fixed with 658bf0d86e0a22033fb3ed6de5bb39bc72483a2b - can you confirm that everything works as expected?

**Comment by piyueh** [comment]
Thanks! It works for my use case to package an Arch AUR package. The AUR package pulls the whole GitHub repository, so the license file will be included in the package without a problem.

I also checked the PyPI package. The license file, however, is not included in the `pip` installation. I guess you may need to add `include LICENSE` to `MANIFEST.in`.

Thanks again for open-sourcing this package!

**Comment by FND** [comment]
Ah, thanks for paying attention (it's been a while since I've been doing any Python packaging... ). Fixed in v0.4.3.
